# Theme
remote_theme: epidrome/cover-card@main

# Title and tag line
title: 'Brain Juice Rides'
description: 'Welcome to my corner of the internet!'

# Images
avatar: 'avatar.jpg'
background: 'background.jpg'
favicon: 'favicon.ico'

# Online profiles
#dribbble: 'mydribbble'
youtube: 'myyoutube'
instagram: 'myinsta'
github-user: 'mygithub'
blog_url: 'myblog.blog.com'
email: 'hello@example.com'

social-links-order: [github-user, facebook, twitter, instagram, tumblr, pinterest, linkedin, youtube, vk, weibo, dribbble, messenger, blog_url, email]

# Yaml manifest of supported social links
# Requirements:
# `name`
#     - plain-text name of the site (e.g. twitter)
#     - **mandatory**
# `url-pattern`
#     - site URL pattern containing a placeholder string (e.g. twitter.com/__USERNAME__)
#     - placeholder will be replaced by username or value specified in _config.yml (e.g. twitter.com/mytwitter)
#     - **mandatory**
# `url-scheme`
#     - the hardcoded URI/URN url-scheme (e.g. https://)
#     - can be one of: ['https://', 'http://', 'mailto:']
#     - defaults to '//'
#     - **optional**
# `icon-class`
#     - the font awesome icon class names
#     - font-awesome free and supports `fas` (solid) and `fab` (brands) styles
#     - defaults to `fab` style and uses value of `name` attribute (e.g. fab fa-2x fa-twitter)
#     - **optional**
social-links:

  - name: instagram
    url-pattern: instagram.com/brainjuicerides

  - name: github-user
    url-pattern: github.com/BrainJuiceRides
    icon-class: fab fa-2x fa-github

  - name: youtube
    url-pattern: youtube.com/channel/UC4aj9s23_Ce3ubPZ9XVcmMg

  - name: blog_url
    url-pattern: '__USERNAME__'
    icon-class: fas fa-2x fa-blog

  - name: email
    url-scheme: 'mailto:brainjuicerides@gmail.com'
    url-pattern: '__USERNAME__'
    icon-class: far fa-2x fa-envelope-open
